Azure/autorest-clientruntime-for-java

- azure-client-runtime/src/main/java/com/microsoft/azure/DAGNode.java
- azure-client-runtime/src/main/java/com/microsoft/azure/DAGraph.java
- azure-client-runtime/src/main/java/com/microsoft/azure/Graph.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #973

- azure-client-runtime/src/main/java/com/microsoft/azure/Graph.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
> [Automatic PR] SDK changes from pull request #983

- azure-client-runtime/src/main/java/com/microsoft/azure/DAGraph.java
- azure-client-runtime/src/main/java/com/microsoft/azure/Graph.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1015

- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1023

- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- build-tools/src/main/resources/checkstyle.xml
> [Automatic PR] SDK changes from pull request #1026

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- build-tools/src/main/resources/checkstyle.xml
- client-runtime/src/main/java/com/microsoft/rest/ServiceCall.java
- client-runtime/src/main/java/com/microsoft/rest/ServiceResponseCallback.java
- client-runtime/src/main/java/com/microsoft/rest/ServiceResponseEmptyCallback.java
> [Automatic PR] SDK changes from pull request #1032

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureServiceClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/RestClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/RequestIdHeaderInterceptorTests.java
- client-runtime/src/main/java/com/microsoft/rest/UserAgentInterceptor.java
> Reduce complexity in RestClient

- azure-client-runtime/src/main/java/com/microsoft/azure/RestClient.java
To be able to use proxy servers with authentication in azure java sdk we need to set proxy authenticator for the rest client.
Issue: Azure/azure-sdk-for-java#1225
> Add ability to use proxy authentication in java rest client

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/UserTokenCredentials.java
Based on the documentation for the class constructor, if environment is
null it should default to AzureEnvironment.AZURE.
> Default to AzureEnvironment.AZURE if environment is set to null

- azure-android-client-authentication/build.gradle
- azure-client-authentication/build.gradle
- azure-client-authentication/pom.xml
- azure-client-runtime/build.gradle
- azure-client-runtime/pom.xml
- build-tools/pom.xml
- client-runtime/build.gradle
- client-runtime/pom.xml
- pom.xml
After merge:
1. Publish following runtime 1.0.0-beta6-SNAPSHOT(s) to sonatype
azure-client-runtime [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/azure-client-runtime/)
azure-client-authentication [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/azure-client-authentication/)
autorest-build-tools [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/autorest-build-tools/)
rest client runtime  [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/rest/client-runtime/)
2. Re-run CI for the PR https://github.com/Azure/azure-sdk-for-java/pull/1444 that requires the above snapshots.
> Release 1.0.0 beta5

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PollingState.java
- azure-client-runtime/src/main/java/com/microsoft/azure/serializer/CloudErrorDeserializer.java
Following are the issues addressed in this PR.
1. The `CloudErrorDeserializer` was not correctly deserializing CloudError from the response of a LRO Azure-AsyncOperation Query. An unsuccessful response looks like
```
{
"startTime": "2017-06-21T20:34:18.679743+00:00",
"endTime": "2017-06-21T20:38:10.607023+00:00",
"status": "Canceled",
"error": {
"code": "OperationPreempted",
"message": "The operation has been preempted by a more recent operation."
},
"name": "59e17e11-aa27-4052-8ab1-d3d93092f8f7"
}
```
In CloudErrorDeserializer::deserialize(..) the [topNode](https://github.com/Azure/autorest-clientruntime-for-java/blob/a7f9826fef1c45d507b2a7abb5fd8ccb83a7b429/azure-client-runtime/src/main/java/com/microsoft/azure/serializer/CloudErrorDeserializer.java#L52) variable is already pointing to …
> Better handling of CloudError 

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureAsyncOperation.java
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureServiceClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PollingState.java
**What is changed in AzureClient?**
***Following methods are added.***
**beginPutOrPatchAsync**
```java
AzureClient.<T> Single<PollingState<T>> 
beginPutOrPatchAsync(Observable<Response<ResponseBody>> observable, 
final Type resourceType)
```
Initiate a LRO PUT or PATCH operation and returns serializable PollingState representing the LRO. This state can be used later to resume the polling.
**beginPostOrDeleteAsync**
```java
AzureClient.<T> Single<PollingState<T>>  
beginPostOrDeleteAsync(Observable<Response<ResponseBody>> observable, 
final Type resourceType)
```
Initiate a LRO POST or DELETE operation and returns serializable PollingState representing the LRO. This state can be used later to resume the polling.
**pollSingleAsync**
```java
AzureClient.<T> Single<PollingState<T>> …
```
> [After 1.0.4] Enabling user to poll long running operations

- client-runtime/src/main/java/com/microsoft/rest/RestException.java
- client-runtime/src/main/java/com/microsoft/rest/v2/EncodedParameter.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodParser.java
- client-runtime/src/main/java/com/microsoft/rest/v2/annotations/ExpectedResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/annotations/ExpectedResponses.java
- client-runtime/src/main/java/com/microsoft/rest/v2/annotations/UnexpectedResponseExceptionType.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpHeader.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/OkHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/RxNettyResponse.java
- client-runtime/src/test/java/com/microsoft/rest/v2/MyRestException.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerInterfaceParserTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerMethodParserTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpHeaderTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpHeadersTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpRequestTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpResponse.java
This pull request addresses [this issue](https://github.com/Azure/autorest-clientruntime-for-java/issues/202).
I added ExpectedResponse and UnexpectedResponseExceptionType annotations. I chose to use UnexpectedResponseExceptionType instead of ErrorResponse because I felt that it better described what the annotation was actually doing.
I also added some tests to improve test coverage and to ensure that RestProxy was doing what we expected.
> Add ExpectedResponse and UnexpectedResponseExceptionType annotations

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/OperationStatus.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/Value.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/InvalidReturnTypeException.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodParser.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerInterfaceParserTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerMethodParserTests.java
This pull request adds support for long running operations with no return type (some delete calls are this way). It also adds support for polling long running operations and returning periodic OperationStatus objects.
> Long running operations

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/ValueTests.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerInterfaceParser.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodParser.java
Originally I liked the idea of having the ResponseHandler interface that RestProxy and AzureProxy would use, but the more I saw it, the less I liked it. This pull request removes that idea in favor of just having AzureProxy inherit from RestProxy. This simplifies many of the helper functions in RestProxy and AzureProxy (no need to pass arguments when they are members of a parent type).
> Remove ResponseHandler, make AzureProxy subclass RestProxy

- azure-client-runtime/src/test/java/com/microsoft/azure/ValueTests.java
- client-runtime/src/main/java/com/microsoft/rest/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpRequest.java
- client-runtime/src/main/java/com/microsoft/rest/http/RxNettyResponse.java
- client-runtime/src/test/java/com/microsoft/rest/RestProxyTests.java
This simply makes it so when a byte[] is passed as a `@BodyParam`, RestProxy uses it as the request body. There are also some small changes that prevent setting multiple Content-Length header values, respect the Content-Type set in `@Headers`, and provide robustness when a server neglects to pass a Content-Length header on a response.
> Support byte[] body params

- azure-client-runtime/src/test/java/com/microsoft/azure/AzureTests.java
- client-runtime/src/main/java/com/microsoft/rest/annotations/HostParam.java
- client-runtime/src/test/java/com/microsoft/rest/RestProxyTests.java
Adds a few simple tests for a service with multiple host parameters. This change is mainly in support of code generator work. I removed the default argument from `@HostParam` because it seems necessary to specify which variable in the raw host is being referenced.
> Add tests for multiple @HostParam attributes

- azure-client-runtime/src/test/java/com/microsoft/azure/AzureProxyToRestProxyTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/http/MockAzureHttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/SwaggerMethodParser.java
- client-runtime/src/test/java/com/microsoft/rest/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/http/MockHttpClient.java
This ensures that the runtime throws IllegalArgumentException when null is passed as the argument for a `@BodyParam`. It also ensure that when null is provided for a query parameter, the entire name/value pair is omitted, and if the empty string is passed, it's rendered like a non-empty string would be, like `?param=&nextparam=something`.
> Throw for null body param

- client-runtime/src/main/java/com/microsoft/rest/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/http/RxNettyAdapter.java
- client-runtime/src/main/java/com/microsoft/rest/http/UrlBuilder.java
- client-runtime/src/test/java/com/microsoft/rest/http/UrlBuilderTests.java
This PR adds support for paging. Cookies are used in the AutoRest tests to track "where" we are in a scenario that takes place over multiple requests, so I added cookie support in RxNettyAdapter.
I also added handling for some of the complex partial URLs that can be returned by services to indicate where the next page is located.
> Paging support

- client-runtime/src/main/java/com/microsoft/rest/ServiceFuture.java
Required the overload `ServiceFuture::fromBody(Completable, ..)` to fix the issue https://github.com/Azure/azure-sdk-for-java/issues/1905
> Adding ServiceFuture::fromBody that takes rx.Completable

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureAsyncOperationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/LocationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PollStrategy.java
- client-runtime/src/main/java/com/microsoft/rest/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/SwaggerMethodParser.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/policy/LoggingPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/CredentialsTests.java
- client-runtime/src/test/java/com/microsoft/rest/RequestIdPolicyTests.java
- client-runtime/src/test/java/com/microsoft/rest/RetryPolicyTests.java
- client-runtime/src/test/java/com/microsoft/rest/UserAgentTests.java
This pull request truly makes RestProxy and AzureRestProxy only have a single path that requests go through. There's no longer a distinction between handling async versus sync methods. All methods go through the async handler, and then the sync versions block on the result.
> Make RestProxy sync scenarios go through async scenarios (one code path)

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureAsyncOperationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/LocationPollStrategy.java
- client-runtime/src/main/java/com/microsoft/rest/RestClient.java
- client-runtime/src/main/java/com/microsoft/rest/http/BufferedHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/http/RxNettyAdapter.java
- client-runtime/src/main/java/com/microsoft/rest/policy/AddCookiesPolicy.java
- client-runtime/src/main/java/com/microsoft/rest/policy/LoggingPolicy.java
1. Migrates cookie management to a CookiePolicy
2. Adds a few extra throw statements to LRO handlers
3. Adds BufferedHttpResponse which is created when a LoggingPolicy needs to read an HttpResponse body into memory.
- I played around with a few alternatives to this and this wound up making sense to me due to the complexity of thread-safe caching of the RxNetty HTTP response that occurs whenever someone first reads it.
- I'm still concerned actually that this will enable some case where a program will only work if HTTP response bodies are being logged, because BufferedHttpResponse has "replayable" response bodies. May need to revisit and decide to actually cache the HTTP response in RxNettyResponse. Maybe the answer is to read the body eagerly in RxNettyResponse.
> Miscellaneous LRO support changes

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/MSICredentials.java
- azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java
- client-runtime/src/main/java/com/microsoft/rest/RestClient.java
- client-runtime/src/main/java/com/microsoft/rest/ServiceFuture.java
- client-runtime/src/main/java/com/microsoft/rest/credentials/BasicAuthenticationCredentials.java
- client-runtime/src/main/java/com/microsoft/rest/credentials/ServiceClientCredentials.java
- client-runtime/src/main/java/com/microsoft/rest/credentials/TokenCredentials.java
- client-runtime/src/main/java/com/microsoft/rest/policy/CredentialsPolicy.java
- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningSerializer.java
- client-runtime/src/test/java/com/microsoft/rest/FlatteningSerializerTests.java
This features a few preliminary changes to the runtime in order to support the management SDK in practice. With these changes, I have our storage accounts and usages tests working :tada:, which is basically all the tests I saw for storage management.
- Put LoggingPolicy at the end of the chain because it lets you see everything that's been done to the HttpRequest.
- Added a Proxy field because AzureConfigurableImpl wanted to be able to set one and our concrete HTTP client can now use one.
- Refactored credentials to reflect that `authorizationHeaderValue` may throw.  Tweaked things so that AzureTokenCredentials will actually try to get a token. Not sure how this stuff can be tested except to run tests in management SDK.
I also merged master in, so some changes e.g. MSICredentials and …
> Azure management support

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/RefreshTokenClient.java
- client-runtime/src/main/java/com/microsoft/rest/RestClient.java
- client-runtime/src/main/java/com/microsoft/rest/http/BufferedHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/http/RxNettyAdapter.java
When working on tests for management SDK, which depend heavily on recording and playing back HTTP traffic, I found a need to specify a mock HTTP client in RestClient. RestClient had a hard reference on RxNettyAdapter so I needed to rework things a bit.
After some experimentation, I settled on this as a pretty good way to create an HTTP client from some commonly-known configuration set. It concerns me a bit that it's, well, factories and builders all the way down, but it seems to be the cost of immutability in Java 7. One alternative would be to take some of these named Factory interfaces and simply use `Func1<Configuration, Result>`. See what you think.
I also think RestClient.Builder deserves a little thought on which parameters are required-- I'd tend to advocate making those required …
> Add HTTP client factory

- azure-client-runtime/src/main/java/com/microsoft/azure/ProvisioningState.java
- azure-client-runtime/src/main/java/com/microsoft/azure/ProvisioningStatePollStrategy.java
I tried running AutoRest tests against the most recent client runtime and they didn't terminate for the reasons implied by these code changes.
1. Canceled is a known conclusive state. Since there might be other values that services give back to indicate the operation is done, it might be best to implement by comparing to InProgress.
2. If the service doesn't give back a provisioning state, best to consider it a failure.
There are several other tests failing, many of which due to the way errors are handled. AutoRest tests expect a non-success completed state to throw an exception. It might be most productive to work on LROs directly against AutoRest tests because they exercise so many failure conditions.
> Fix endless loop in AutoRest Azure tests

- client-runtime/src/main/java/com/microsoft/rest/SwaggerMethodParser.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpHeaders.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpRequest.java
- client-runtime/src/main/java/com/microsoft/rest/http/NettyResponse.java
- client-runtime/src/main/java/com/microsoft/rest/policy/AddCookiesPolicy.java
- client-runtime/src/main/java/com/microsoft/rest/policy/CredentialsPolicy.java
- client-runtime/src/main/java/com/microsoft/rest/policy/RequestIdPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/http/HttpHeadersTests.java
- client-runtime/src/test/java/com/microsoft/rest/http/MockHttpClient.java
This PR removes the add() method in favor of the set() method because add() has proven to be a behavior that people generally pick by accident and don't really intend. Other minor changes were made in order to fix the autorest.java headers tests.
We should consider making HttpHeaders immutable, as well as HttpRequest itself, as opposed to providing methods for deep copying.
> Remove HttpHeaders.add()

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureServiceClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/CredentialsPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestClientTests.java
- Renames `addCustomPolicy` to `addRequestPolicy`
- Adds `setRequestPolicies(List<RequestPolicy.Factory)`
- Renames `withCredentials(ServiceClientCredentials)` to `withCredentialsPolicy(RequestPolicy.Factory)`
- Removes `withMaxIdleConnections(int)`
The point of "add" instead of "with" is to convey that repeatedly calling it doesn't cause the previous value to get overwritten. Not sure whether it's more consistent to use the name `withRequestPolicies` instead of `setRequestPolicies`.
> Rename RestClient methods

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/PollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/ProvisioningStatePollStrategy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
There were some cases where IOExceptions produced by Jackson were wrapped into RuntimeExceptions and we failed to catch them as IOExceptions. This is part of why autorest.java LRO tests fail in the cases where invalid JSON is provided.
The deserialize convenience methods that `throw Exceptions.propagate(Exception)` were probably just there because it's cumbersome to wrap things in try/catch inside your map in Rx. The functional interfaces in RxJava 2 allow throwing checked exceptions, so this will pretty much be a non-issue after we migrate.
> Fix handling of checked exceptions from serialization

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureRestClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureServiceClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureTests.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/ServiceClient.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestClientTests.java
This PR adds `DEFAULT` and `newDefaultBuilder()` static members to create RestClient, as well as an AzureRestClient class with similar members. The RestClient.Builder constructor itself now takes all its required parameters as constructor arguments. The RestClient.Builder constructor with no arguments has been deprecated.
> Add default RestClient instances and required parameters in builder constructors

- client-runtime/src/main/java/com/microsoft/rest/v2/http/UrlBuilder.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/PortPolicy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/RequestPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/UrlBuilderTests.java
I added this method because I need to modify a URL in autorest.java and I need to check if a port already exists. If it doesn't, then I need to add it. java.net.URL doesn't allow me to check if the port already exists, otherwise I would've just used that.
> Add UrlBuilder.parse()

- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
Small fixes to support AsyncInputStream return type and to add a Content-Length: 0 header when the request has no body.
I'm thinking it'll be simplest to have AsyncInputStream instead of Flowable<byte[]> for both download and upload for consistency. Also, AsyncInputStream may acquire a `close()` method down the line which would dispose of an unwanted connection a bit more elegantly than `stream.content().subscribe().dispose()`.
> AsyncInputStream and null body length

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
This makes it so when a Single<HttpResponse> coming from NettyClient is disposed before completion, the channel will be closed, causing the ongoing upload to be canceled.
Also adds several checks to responseEmitter.isDisposed before emitting errors. This is because RxJava will dump big stack traces into your logs if you try to emit an error from a stream that's already been disposed. These are errors people probably won't care about considering they canceled the request that caused the error anyway.
> Cancellation for file uploads

- pom.xml
resolves #333
added a maven shading profile to package jar to include jackson artifact packages to avoid conflict while running in spark environment.
The way the library packaging is to be changed. Here is the maven running order to create the artifacts with proper packaging
```
mvn clean install 
mvn clean install -pl azure-client-authentication -P run-shade-plugin
mvn clean install -pl azure-client-runtime -P run-shade-plugin
```
Run fine in spark environment 
Dependency conflict running the library in spark environment due to jackson-core and jackson-databind. Spark (2+) uses jackson version 2.6.5 where as this library uses version 2.7.2
```
01:39:43,346  INFO [Thread-6] ExecuteScript:58 - Exception in thread "main" java.lang.NoSuchMethodError: …
```
> fix to avoid dependency conflict on jackson in spark environment

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
This causes a simpler error type to be received by `onErrorResumeNext`. Before, you'd get a CompositeException containing an IOException and a RuntimeException containing the same IOException, and now you get just the IOException.
> Use Single.error instead of throw Exceptions.propagate

- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodParser.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
This solves a problem that Storage raised. They have an API that has an optional body parameter. In the runtime, we were previously always throwing an exception on a null body argument if the method had a parameter with a BodyParam annotation, which means that they were unable to call their API because it would always throw an exception when they passed in null (which is a valid value for an optional parameter).
This is one possible fix for this problem. Another would be to add an argument for BodyParam that indicates whether or the parameter is required. The fix that I chose seemed much easier.
> Remove check for null body parameter and get tests to pass

- client-runtime/src/main/java/com/microsoft/rest/v2/policy/HttpLogDetailLevel.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/HttpLoggingPolicyFactory.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
I removed the prettyJSON field from LogLevel (now called HttpLogDetailLevel) because it seemed wrong to share mutable state between all users of an enum value. It's now an optional argument to HttpLoggingPolicyFactory and I'm actually accounting for it when I log the body. This is helpful when debugging azure-libraries-for-java tests.
> Add flag to pretty print JSON HTTP bodies

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/ProvisioningStatePollStrategy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- LROs emit the first HttpResponse when polling as well as emitting subsequent polling responses.
- Empty bodies are now tolerated when a ProvisioningStatePollStrategy completes in order to accept the real-world behaviors of `ResourceGroups.delete`.
- Fix in NettyClient where we violated Reactive Streams spec by throwing in onSubscribe(Subscriber) instead of calling `Subscriber.onError`
- Experimental/trivial tweak to `RestProxy.instantiateUnexpectedException` while working with RxJava tracing tools.
> LRO tweaks

- client-runtime/src/main/java/com/microsoft/rest/v2/RestException.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
- client-runtime/src/main/java/com/microsoft/rest/v2/protocol/HttpResponseDecoder.java
Directly passing exceptions that say stuff like "unexpected EOF" or "expected ')'," or stuff like that seems not so useful to users as simply saying there were malformed headers or a malformed body on the response.
Also going on my radar is the idea of detecting if a response has not yet been decoded in RestProxy and if so simply decoding it.. it's cumbersome to track down failures where we forgot to put a DecodingPolicyFactory in the pipeline. It's a rare REST method which has no schema defined for its response headers, response body, or error body.
> Wrap exceptions generated from deserialization and other minor tweaks

- azure-client-authentication/src/test/java/com/microsoft/azure/v2/credentials/RefreshTokenClientTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/HttpLoggingPolicyFactory.java
- client-runtime/src/main/java/com/microsoft/rest/v2/util/FlowableUtil.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyXMLTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
There is a FlowableUtil.collectBytes() method that produces a `Single<byte[]>`, but we're transitioning over to using `ByteBuffer` instead of `byte[]`, so I renamed that method and created a new one that returns a `Single<ByteBuffer>`.
> Add FlowableUtil.collectBytesInBuffer()

- client-runtime-native/pom.xml
- client-runtime/pom.xml
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- pom.xml
This is my proposal for #362. By default, people who grab our runtime and libraries that depend on our runtime will use the transport and SSL based on the Java standard library. But if they want the increased performance (and potential bugs) they can add this dependency:
```xml
<dependency>
<groupId>com.microsoft.rest.v2</groupId>
<artifactId>client-runtime-native</artifactId>
<version>2.0.0-SNAPSHOT</version>
<type>pom</type>
</dependency>
```
Then each SDK's README should show this dependency in the "how to install" section next to the SDK dependency itself.
This will add either epoll or kqueue transport if applicable, and will also add a statically-linked boringssl dependency on windows/linux/mac. Users who want fine grained control over the SSL implementation used (e.g., I know we'll …
> Add client-runtime-native module

- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
- pom.xml
- Gets rid of [https://netty.io/4.1/api/io/netty/handler/ssl/util/InsecureTrustManagerFactory.html](InsecureTrustManagerFactory) so that Netty will use the system default TrustManager instead.
- Bumps to Netty 4.1.21 so that we get the ReadOnlyDirectByteBuffer fix for native transports
> Update to Netty 4.1.21 and test read-only memory mapped file

- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodParser.java
- client-runtime/src/main/java/com/microsoft/rest/v2/annotations/HeaderParam.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
This adds support for writing x-ms-header-collection-prefix header parameters. It doesn't support reading x-ms-header-collection-prefix headers from a response. That needs to be done in a separate pull request.
> Add support for x-ms-header-collection-prefix extension

- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/AuthFile.java
- azure-client-authentication/src/test/java/com/microsoft/azure/v2/credentials/RefreshTokenClientTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/BufferedHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/ProxyAuthenticationPolicyFactory.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithMockTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyXMLTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
- There were some runtime errors on the Windows command line because we were using `new String(byte[])` instead of `new String(byte[], StandardCharsets.UTF_8)`.
- Changed all current usages of Guava Charsets to use StandardCharsets in the hope of loosening our grip on that dependency
> Always specify charset when using new String()

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
- azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java
Truststore with certs loaded at runtime fail if the SSLSocketFactory is not set.
We use a custom truststore for certs, The certs are loaded at runtime and even though we pass the RestClient with the OkHttpClient and SSLSocketFactory the certs loaded at runtime are not identified.
We get the error:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Since SslSocketFactory was never passed to AuthenticationContext it was not able to detect the certs loaded at runtime. With the change above we can now pass SslSocketFactory at runtime. …
> Added option to set SSLSocketFactory on ApplicationTokenCredentials

- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/RefreshTokenClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyToRestProxyWithNettyTests.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClientConfiguration.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClientFactory.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithHttpProxyNettyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithNettyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/NettyClientTests.java
Users should be able to free the resources associated with an HttpClient when they're done using it. This PR makes it so:
- All default HTTP pipelines share a static, lazy instantiated HttpClientFactory so that we don't leak the implicitly created resources (EventLoopGroups, channels)
- Manually created HttpPipelines require users to hold on to the HttpClientFactory and close it if they want to reclaim the resources
- The only alternative I can really think of for this is to add shutdown() methods to HttpPipeline and/or HttpClient themselves and to put a ref count on the HttpClient.Factory-- seems overly complicated
Addresses #372.
> Add shutdown() method to HttpClient.Factory

- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpResponse.java
A tester found an interesting problem where when we issue many HttpRequests, the responses eventually hang. This was tracked down to the fact that the RestResponse body type was Void and we were discarding the HttpResponse instead of either closing it or reading it. This normally wouldn't be a problem, except with a chunked encoding where there are still body bytes to read to basically indicate the end of the response content.
This fix assumes that the only content to read is going to be such a content, like a trailing `"0\n"` string or similar. I read and discard the body content when the body is Void because it seems preferable to closing the response which would result in the connection being closed.
> Fix Void response body connection leak

- azure-client-authentication/pom.xml
- azure-client-runtime/pom.xml
- client-runtime/pom.xml
- client-runtime/src/main/java/com/microsoft/rest/v2/BodyResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/StreamResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodParser.java
- client-runtime/src/main/java/com/microsoft/rest/v2/VoidResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/protocol/HttpResponseDecoder.java
- client-runtime/src/main/java/com/microsoft/rest/v2/util/FlowableUtil.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- pom.xml
This adds runtime support for concrete RestResponse subtypes.
The approach I'm using in the generator is basically thus:
- If a Headers type is defined, a Response type will be generated to contain the Headers and Body
- If no Headers type is defined, we will use `BodyResponse<TBody>`
- If only a `Flowable<ByteBuffer>` body is defined, we will use `StreamResponse`.
- If neither Headers or Body are defined we will use `VoidResponse`.
I've done a good amount of testing through autorest.java but will make sure to add some unit tests, perhaps updating RestProxyTests to use these new types before merging.
> Add RestResponse subtypes and handling

- client-runtime/pom.xml
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClientFactory.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/CookiePolicyFactory.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/NettyClientTests.java
- pom.xml
- Gets rid of Apache Commons, which we appear to only have ever used in one instance in the entire runtime. Using Java 8's String.join() instead.
- Changed `Completable HttpClientFactory.shutdown()` to `void HttpClientFactory.close()` as this is not a context where optimizing the utilization of threads is useful and it's better to have something straightforward that conforms to the `Closeable` interface
> Various minor improvements

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
Fixes #389
- Converted the SingleOnSubscribe to lambda--sorry about the spurious diffs simply due to unindenting.
- Added a missing `subscription.cancel()` for the request content when writing to channel fails so that we stop reading from the request stream
- Introduced `draining` flag in NettyClient.java:402. This makes it so we don't push on additional stack frames for each item we emit from the queue in the case where the response `subscriber.onNext` makes a synchronous call to `subscription.request()`. The queue generally contains a small number of items, so this wasn't a big crash risk, but it's incorrect to leave it the way it originally was.
(Still interested in the potential for a solution that relies more heavily on RxJava operators for response content streaming, but it will …
> Fix reentrant safety in ResponseContentFlowable

- client-runtime/pom.xml
- pom.xml
I removed this dependency a little while back, but didn't actually stamp out its usages in the generated code, so I'm bringing it back until I can put in the time to remove it properly. This fixes build errors in some of our user's projects related to base64 encoding.
> Add back apache commons for now

- .gitignore
- azure-client-authentication/src/test/java/com/microsoft/azure/v2/credentials/http/MockHttpResponse.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureAsyncOperationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/ProvisioningStatePollStrategy.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpResponse.java
- client-runtime/pom.xml
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/BufferedHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/HttpLoggingPolicyFactory.java
- client-runtime/src/main/java/com/microsoft/rest/v2/protocol/HttpResponseDecoder.java
- client-runtime/src/main/java/com/microsoft/rest/v2/util/FlowableUtil.java
- client-runtime/src/test/java/com/microsoft/rest/v2/MockServer.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpResponse.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/NettyClientTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/policy/RequestIdPolicyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/util/FlowableUtilTests.java
As promised in discussion in #402, this is a rework of `NettyClient.ResponseContentFlowable`.
The Flowable has been reworked to
* perform proper request accounting
* ensure reads are requested one at a time of upstream only on completion of last requested read (because `channel.read()` is ignored by Netty if a read is pending)
* buffer `ByteBuf`s as upstream delivers many items at a time (a *chunk*)
* release unused `ByteBuf`s on cancellation 
* handle asynchronous calls to `subscribeActual`, `request`, `cancel` with non-blocking techniques
* handle a connection failure by also propagating the `channelInactive` response to the Flowable (which emits an `IOException`)
* reject multiple subscriptions by emitting an error
* be compliant with reactive-streams contract (bad requests reported to …
> v2 NettyClient flowable rework

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
- client-runtime/src/test/java/com/microsoft/rest/v2/MockServer.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyStressTests.java
Essentially a continuation of #406 
- Adds `finishedWritingRequestBody` flag to determine whether a channel should be closed when a response body is finished reading. This lets us pass `RestProxyStressTests.testHighParallelism` in a reasonable amount of time (~5 seconds) instead of either running for about a minute or just failing due to being unable to open more ports.
- This perhaps should be changed so that we just close the connection if the request hasn't been fully written at the time we receive the response status/headers.
- Other minor refinements/trimming dead code
- Attempting to make RestProxyStressTests easier to run automatically, with everything able to run against the local test server.
- Trying to get the test server to spawn automatically with the tests, but it's …
> Netty client rework 2

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/util/FlowableUtil.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/NettyClientTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/util/FlowableUtilTests.java
Based on a request from Storage that cases where we accidentally provide the wrong Content-Length should result in an error, not in a hang or in the HTTP request completing without sending all the bytes in the stream.
Fixes #395
> Add CountingOperator and tests

- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningSerializer.java
- client-runtime/src/test/java/com/microsoft/rest/FlatteningSerializerTests.java
Repro --
```java
@JsonFlatten
public class School {
@JsonProperty(value = "teacher")
private Teacher teacher;
public School withTeacher(Teacher teacher) {
this.teacher = teacher;
return this;
}
}
```
```java
public class Teacher {
@JsonProperty(value = "students")
private Map<String, Student> students;
public Teacher withStudents(Map<String, Student> students) {
this.students = students;
return this;
}
}
```
```java
public class Student {
}
```
```java
public static void main( String[] args ) throws IOException {
Teacher teacher = new Teacher();
Map<String, Student> students = new HashMap<String, Student>();
students.put("af.B/C", new Student());
students.put("af.B/D", new Student());
teacher.withStudents(students);
School inr = new School();
inr.withTeacher(teacher);
String serialized = …
```
> Ensure map key with dot is getting serialized correctly

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- pom.xml
- Update Netty version
- Use .split() to ensure we don't attempt to encode an excessively large buffer with SSL before sending
- This magic number 8192 can be adjusted-- maybe 1024*64 is better?
> Update Netty and break apart large buffers

- client-runtime/src/main/java/com/microsoft/rest/v2/http/UnexpectedLengthException.java
- client-runtime/src/main/java/com/microsoft/rest/v2/util/FlowableUtil.java
- client-runtime/src/test/java/com/microsoft/rest/v2/util/FlowableUtilTests.java
@rickle-msft
This enables the consumer of the ensureLength error to consume and rethrow with a better contextual message (e.g. in the context of retries)
> Add UnexpectedLengthException

- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/RefreshTokenClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyToRestProxyWithNettyTests.java
- client-runtime/pom.xml
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClientConfiguration.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithHttpProxyNettyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithNettyTests.java
- pom.xml
Related to #451 
I've finally gotten a grip on [how HTTPs proxying actually works](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java#L155) and am making changes as appropriate--including just relying on Netty's HttpProxyHandler to do the job.
This change seems like the right direction--we pass the destination address to channel.connect(), and pass the proxy address to HttpProxyHandler.
I've fixed the remaining issues by always using `HttpClientCodec` instead using of `HttpRequestEncoder` and `HttpResponseDecoder`. I think we were putting the pipeline in an inconsistent state by manipulating it from outside the event loop thread.
> Fix HTTPS proxying

- azure-client-runtime/src/main/java/com/microsoft/azure/CloudError.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PolicyViolation.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PolicyViolationErrorInfo.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TypedErrorInfo.java
- azure-client-runtime/src/main/java/com/microsoft/azure/serializer/CloudErrorDeserializer.java
- azure-client-runtime/src/main/java/com/microsoft/azure/serializer/TypedErrorInfoDeserializer.java
- azure-client-runtime/src/test/java/com/microsoft/azure/CloudErrorDeserializerTests.java
'additionalInfo', a new property added to ARM error contract, contains additional error information. For example, it will contain detailed policy violation error information when the request to ARM failed due to violation of Azure policies.
The changes are to allow deserializing additionalInfo in ARM error based on the error type.
> Add additionalInfo to CloudError

- .travis.yml
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
This state machine doesn't appear to do anything because all the writes occur on the event loop anyway. We can rely on channel.isWritable() and the nature of the single event loop thread running for the channel to prevent multiple simultaneous requests for request content.
@rickle-msft
> Remove channel writing state machine

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java
This pull request is coming form Isobar  The modifications contained will enable us to utilize this latest (v2) version of the Azure Storage on the AF CCE project.    The actual  changes are simple and they enable passing in an SslContext to the underlying NettyClient implementation of HttpClient.  This was done via an overloaded constructor.  Existing constructor signatures were left and reference the new implementation by passing in null for the SslContext which will cause the SSL behavior to fallback to the previous (now default) behavior.
> Added configurability of SSL Context

- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningDeserializer.java
- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningSerializer.java
- client-runtime/src/test/java/com/microsoft/rest/AnimalShelter.java
- client-runtime/src/test/java/com/microsoft/rest/AnimalWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/CatWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/DogWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/FlattenableAnimalInfo.java
- client-runtime/src/test/java/com/microsoft/rest/FlatteningSerializerTests.java
- client-runtime/src/test/java/com/microsoft/rest/RabbitWithTypeIdContainingDot.java
1. Handle typeId (JsonTypeInfo) containing dots (Fixes: https://github.com/Azure/autorest-clientruntime-for-java/issues/598)
2. Handle escaped property key
3. Ensure all POJOs goes through flattening encoder and decoder (hence ignore JsonFlatten annotation)
4. TypeId related autorest PR https://github.com/Azure/autorest.java/pull/336
> Updating Flattening encoder-decoder to handle JsonTypeInfo

- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningDeserializer.java
- client-runtime/src/test/java/com/microsoft/rest/FlatteningSerializerTests.java
Updating FlatteningDeserializer to handle objects that only contain
"@odata.type" field and no additional properties
> Fix for issue #613

- azure-client-runtime/src/main/java/com/microsoft/azure/serializer/CloudErrorDeserializer.java
- azure-client-runtime/src/test/java/com/microsoft/azure/AzureAsyncOperationDeserializerTests.java
> Fix for issue #612

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/MSICredentials.java
Adding a custom timeout param that the user can add to make sure we cap
the total retry timeout to the user specified value.
Fix for issue #619
> Fix for issue #619

- pom.xml
- The version of adapter-rxjava that was used (2.4.0) was marked as vulnerable in 2 CVEs:  CVE-2018-1000844, CVE-2018-1000850
> Upgrade adapter-rxjava to 2.6.2

- azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java
For requests to Key Vault (`*.vault.azure.net/...`), the current version of `AzureTokenCredentials.getToken(...)` will get an access token for the resource `https://vault.azure.net/` and include it in the request.
However, Key Vault only accepts `https://vault.azure.net` (without the trailing slash) as a valid audience in its access tokens, so this request will _always_ result in a 401 response. This results in at least one unnecessary token request (the initial token request for `https://vault.azure.net/`), and one failed request to Key Vault (followed by the subsequent successful request with the correct token).
(Things eventually work because following a 401 response, the library will retry the token request (now for the correct resource value, obtained from the `WWW-Authenticate` …
> Fixes Key Vault default resource value

- azure-arm-client-runtime/src/main/java/com/microsoft/azure/arm/collection/SupportsBatchCreation.java
- azure-arm-client-runtime/src/main/java/com/microsoft/azure/arm/model/Creatable.java
- build-tools/src/main/resources/checkstyle.xml
- client-runtime/src/main/java/com/microsoft/rest/protocol/ResponseBuilder.java
- client-runtime/src/main/java/com/microsoft/rest/protocol/SerializerAdapter.java
- pom.xml
Fix security alerts on the github repo main page.
> Fix security warning.

- client-runtime/src/main/java/com/microsoft/rest/ServiceFuture.java
Added `volatile` to ServiceFuture's `valueSet` flag, so in case `isCancelled` gets called from a thread other than the subscribe thread the calling thread sees the value change. Based on @anuchandy's comment [here](https://github.com/Azure/autorest-clientruntime-for-java/pull/665#discussion_r421031830).
> Added volatile to ServiceFuture's valueSet flag

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
What happened:
In a long running operation, the user might get exception during polling. For example, the exception might be caused by networking timeout. In such case, the polling stops while the LRO still keep alive at server end.
What expected:
To support better user experience, there should be scenario to resume the polling if the LRO still exists.
This is a simple plan to add retry scenario with fixed 5 retry counts for each exception during the polling.
> add retry scenario for lro polling

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
Before: The error will be ignored if it's not `CloudException`.
After: It would throw the error if it is `CloudException` or last retry attempt is completed.
> handle exceptions during lro polling

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
fix https://github.com/Azure/azure-libraries-for-java/issues/1333
The case in IcM is that:
1. PUT, return retry-after 10
2. GET, return retry-after 30, etc.
And current runtime skipped the 10sec between step1 and step2.
In this PR, I added one additional operator to do this retry-after delay specified in activation response (on condition that it is not in terminal state).
@jianghaolu @anuchandy @ChenTanyi @xccc-msft @yungezz
> add initial delay on retry-after, after activation, before 1st get

- azure-client-runtime/src/main/java/com/microsoft/azure/EvaluationDetails.java
- azure-client-runtime/src/main/java/com/microsoft/azure/ExpressionEvaluationDetails.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PolicyViolation.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PolicyViolationErrorInfo.java
- azure-client-runtime/src/test/java/com/microsoft/azure/CloudErrorDeserializerTests.java
`PolicyViolationErrorInfo` is missing `@JsonIgnoreProperties(ignoreUnknown = true)` annotation and `ObjectMapper` wasn't configured for ignoring unknown fields.
This caused an exception when Azure returned `evaluationDetails` in it's response, making impossible to handle the error gracefully.
In this commit:
- Configured `ObjectMapper` with `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to avoid issues when a new field is introduced on Azure side
- created `EvaluationDetails` and subsequent classes to parse the response
- added `toString` implementation for related and newly created classes for easier logging
- added unit test to verify the parsing
> Add policy evaluation details related classes

- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningDeserializer.java
- client-runtime/src/test/java/com/microsoft/rest/AdditionalPropertiesSerializerTests.java
- client-runtime/src/test/java/com/microsoft/rest/AnimalWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/CatWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/DogWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/NonEmptyAnimalWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/RabbitWithTypeIdContainingDot.java
- client-runtime/src/test/java/com/microsoft/rest/TurtleWithTypeIdContainingDot.java
Types referenced in flattened types are not handled properly: https://github.com/Azure/autorest.java/issues/873
> Backport flattening deserializer to track 1
