- azure-client-runtime/build.gradle
This is a test push from inside submodule.
> Use snapshot in build.gradle in azure-client-runtime

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
Reverts Azure/autorest-clientruntime-for-java#9
> Revert "Fixing UnsupportedOperation exception in PagedList"

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
Reverts Azure/autorest-clientruntime-for-java#10
> Revert "Revert "Fixing UnsupportedOperation exception in PagedList""

- azure-client-authentication/build.gradle
- azure-client-runtime/build.gradle
- build-tools/src/main/resources/checkstyle.xml
- client-runtime/build.gradle
- client-runtime/src/main/java/com/microsoft/rest/Base64Url.java
- client-runtime/src/main/java/com/microsoft/rest/ServiceClient.java
- client-runtime/src/main/java/com/microsoft/rest/serializer/Base64UrlSerializer.java
- client-runtime/src/main/java/com/microsoft/rest/serializer/JacksonMapperAdapter.java
Reverts Azure/autorest-clientruntime-for-java#24
> Revert "Revert "Changes from AutoRest & SDK""

- .travis.yml
> [Automatic PR] SDK changes from pull request #975

- .travis.yml
> [Automatic PR] SDK changes from pull request #970

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
> [Automatic PR] SDK changes from pull request #1007

- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
> [Automatic PR] SDK changes from pull request #1021

- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
> [Automatic PR] SDK changes from pull request #1025

- azure-client-runtime/src/main/java/com/microsoft/azure/Graph.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
> [Automatic PR] SDK changes from pull request #1008

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1060

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1045

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1055

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1061

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1054

- azure-client-runtime/src/main/java/com/microsoft/azure/PagedList.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroup.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskGroupBase.java
- azure-client-runtime/src/main/java/com/microsoft/azure/TaskItem.java
> [Automatic PR] SDK changes from pull request #1063

- client-runtime/src/main/java/com/microsoft/rest/ServiceResponseBuilder.java
- client-runtime/src/main/java/com/microsoft/rest/interceptors/LoggingInterceptor.java
> Work around case insensitive headers

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/ApplicationTokenCredentials.java
- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/RefreshTokenClient.java
- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/UserTokenCredentials.java
- azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java
- pom.xml
> Support proxy in azure token credentials

- azure-client-runtime/src/main/java/com/microsoft/azure/serializer/CloudErrorDeserializer.java
Fixes Azure/azure-sdk-for-java#1858
> Case insensitive cloud error deserializing

- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureTests.java
- client-runtime/src/main/java/com/microsoft/rest/v2/EncodedParameter.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/Substitution.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerInterfaceProxyDetails.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerMethodProxyDetails.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpRequest.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/OkHttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/OkHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/UrlBuilder.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/package-info.java
- client-runtime/src/test/java/com/microsoft/rest/v2/EncodedParameterTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SubstitutionTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerInterfaceProxyDetailsTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerMethodProxyDetailsTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/URLBuilderTests.java
This pull request rearranges the classes used for the Annotation parser/RestProxy. It also adds several tests.
> Annotation parser refactor

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- client-runtime/src/main/java/com/microsoft/rest/RestClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/SwaggerInterfaceParser.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/LoggingPolicy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/UserAgentPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/SwaggerInterfaceParserTests.java
This also includes a few minor fixes to get some basic AutoRest.Java tests passing.
> Add baseURL parameter to RestProxy.

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureAsyncOperationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/LocationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/OperationResource.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/OperationStatus.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/PollStrategy.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpClient.java
- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
This pull request adds support for long running operations that use the Location or the Azure-AsyncOperation protocols.
> Add support for Location and Azure-AsyncOperation long running operations

- azure-client-runtime/src/main/java/com/microsoft/azure/util/ServiceFutureUtil.java
- azure-client-runtime/src/main/java/com/microsoft/azure/util/package-info.java
- client-runtime/src/main/java/com/microsoft/rest/ServiceFuture.java
- client-runtime/src/main/java/com/microsoft/rest/http/RxNettyAdapter.java
We're still deciding on what the future of our futures should be, so I'm adding this type back to prevent the need for lots of AutoRest generator changes in the meantime.
> Add ServiceFuture back for now

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureAsyncOperationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/CompletedPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/LocationPollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/PollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/ProvisioningState.java
- azure-client-runtime/src/main/java/com/microsoft/azure/ProvisioningStatePollStrategy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/ResourceWithProvisioningState.java
- azure-client-runtime/src/test/java/com/microsoft/azure/AzureProxyTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/MockResource.java
- azure-client-runtime/src/test/java/com/microsoft/azure/http/MockAzureHttpClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/http/MockAzureHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/http/BufferedHttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/http/HttpResponse.java
- client-runtime/src/main/java/com/microsoft/rest/policy/LoggingPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/http/MockHttpResponse.java
Add the missing polling strategy (ProvisioningState). This pull request also adds a CompletedPollStrategy, which takes the place of the previous null PollStrategy.
> Add provisioning state poll strategy

- client-runtime/src/main/java/com/microsoft/rest/serializer/FlatteningSerializer.java
- client-runtime/src/test/java/com/microsoft/rest/FlatteningSerializerTests.java
> Fix a regression in flattening serializer

- pom.xml
> Update OkHttp to 3.4

- client-runtime/src/main/java/com/microsoft/rest/v2/http/ByteArrayHttpRequestBody.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/FileRequestBody.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpRequest.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpRequestBody.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/InputStreamHttpRequestBody.java
- client-runtime/src/main/java/com/microsoft/rest/v2/policy/RetryPolicy.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpPipelineTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpRequestTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/InputStreamHttpRequestBodyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/policy/ProxyAuthenticationPolicyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/policy/RequestIdPolicyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/policy/RetryPolicyTests.java
Jeffrey and Josh specifically asked for this.
> Add InputStream support for HttpRequestBody

- build-tools/src/main/resources/checkstyle.xml
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyResponse.java
- pom.xml
This was causing a platform-specific deserialization issue.
> Remove Charsets.defaultCharset()

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
HttpResponse bodies with no content (e.g. most DELETE operations) are represented with a Maybe.empty(), which produces an empty sequence when converted to Observable. This makes it so when you try to get the first response value on a long-running DELETE, you actually make the first GET and return the value from that.
This replaces the value in the Maybe.empty() with an OperationStatus with a null value inside so that the unnecessary GET doesn't occur.
> Emit OperationStatus corresponding to Void response

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/DelegatedTokenCredentials.java
fixes #350 
Signed-off-by: Suraj Acharya <suraj.spa@gmail.com>
>  applicationCredentials is set to null even when passed

- client-runtime/src/main/java/com/microsoft/rest/v2/util/ByteBufferUtil.java
- client-runtime/src/test/java/com/microsoft/rest/v2/util/ByteBufferUtilTests.java
Add a ByteBufferUtil class that can convert from ByteBuffers to byte[]s.
> Add ByteBufferUtil and tests

- client-runtime/src/main/java/com/microsoft/rest/v2/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/UrlBuilder.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/UrlBuilderTests.java
> addQueryParameter() -> setQueryParameter()

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/PollStrategy.java
This was preventing publishing snapshots.
> Fix spelling in PollStrategy Javadoc

- README.md
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpPipelineBuilder.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpPipelineBuilderTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/HttpPipelineTests.java
> Update README.md and add convenience HttpPipelineBuilder methods

- azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java
Fix for https://github.com/Azure/azure-libraries-for-net/issues/384
> Fixed US Gov AD endpoint

- ChangeLog.txt
- README.md
- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/RefreshTokenClient.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyToRestProxyWithNettyTests.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/HttpClientConfiguration.java
- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithHttpProxyNettyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyWithNettyTests.java
- pom.xml
> Support custom port for https proxy

- azure-client-runtime/src/main/java/com/microsoft/azure/v2/OperationState.java
Fixes https://github.com/Azure/autorest-clientruntime-for-java/issues/466
> ProvisioningStateStrategy should not poll if there is no provisioningState property

- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/ApplicationTokenCredentials.java
- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/AzureCliCredentials.java
- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/AzureCliSubscription.java
- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/MSICredentials.java
- azure-client-authentication/src/main/java/com/microsoft/azure/v2/credentials/UserTokenCredentials.java
- azure-client-authentication/src/test/java/com/microsoft/azure/v2/credentials/UserTokenCredentialsTests.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/AzureProxy.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/credentials/AsyncServiceClientCredentials.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/credentials/AzureTokenCredentials.java
- azure-client-runtime/src/main/java/com/microsoft/azure/v2/policy/AsyncCredentialsPolicyFactory.java
> Support async adal authentication

- client-runtime/src/main/java/com/microsoft/rest/v3/RestProxy.java
- client-runtime/src/main/java/com/microsoft/rest/v3/http/HttpPipeline.java
Ref: https://github.com/Azure/autorest-clientruntime-for-java/issues/575
> Adding HttpPipeline::ctr that takes list

- azure-client-runtime/src/test/java/com/microsoft/azure/v2/AzureProxyToRestProxyTests.java
- azure-client-runtime/src/test/java/com/microsoft/azure/v2/http/MockAzureHttpClient.java
- client-runtime/src/test/java/com/microsoft/rest/v2/RestProxyTests.java
- client-runtime/src/test/java/com/microsoft/rest/v2/http/MockHttpClient.java
- client-runtime/src/test/java/com/microsoft/rest/v2/util/FlowableUtilTests.java
> Fix tests based on httpbin changes

- client-runtime/src/test/java/com/microsoft/rest/v2/serializer/JacksonAdapterTests.java
- pom.xml
Addressing https://github.com/Azure/azure-storage-java/issues/454 and https://github.com/Azure/autorest-clientruntime-for-java/issues/600
\\cc @jianghaolu  @rickle-msft
> [V2] Upgrading jackson from 2.8.11 to 2.9.6

- client-runtime/src/main/java/com/microsoft/rest/v2/http/NettyClient.java
Resovles https://github.com/Azure/azure-storage-java/issues/440
> Make emitError() more resilient for more errors

- README.md
- azure-arm-client-runtime/pom.xml
- azure-client-authentication/pom.xml
- azure-client-runtime/pom.xml
- build-tools/pom.xml
- client-runtime/pom.xml
- pom.xml
Please rebase and merge as needed.
> Release 1.6.8

- azure-client-authentication/src/main/java/com/microsoft/azure/credentials/AppServiceMSICredentials.java
Fix for issue #617
Code is based on:
https://github.com/Azure/azure-sdk-for-java/blob/master/authorization/msi-auth-token-provider-jar/src/main/java/com/microsoft/azure/msiAuthTokenProvider/MSICredentials.java#L177
> Add support for User assigned identitied to the app service cred

- azure-arm-client-runtime/pom.xml
- azure-arm-client-runtime/src/test/java/com/microsoft/azure/arm/core/InterceptorManager.java
- azure-client-authentication/pom.xml
- azure-client-runtime/pom.xml
- build-tools/pom.xml
- client-runtime/pom.xml
- pom.xml
Fixes https://github.com/Azure/azure-sdk-for-java/issues/3939
> Update okhttp to latest 3.14

- .gitignore
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
Need this support to update the latest resource swagger spec for the whatif operation?
> Add support of LRO for postOrDelete.

- client-runtime/src/main/java/com/microsoft/rest/serializer/AdditionalPropertiesDeserializer.java
> prevent NPE in deserialize for fields without annotation

- pom.xml
fix https://github.com/Azure/azure-sdk-for-java/issues/1653
> feat: update annotations to fix RELEASE_7 warning

- pom.xml
Updates the retrofit dependency which pulls in an old version of jackson-databind.
> Updating retrofit dependency

- client-runtime/src/main/java/com/microsoft/rest/ServiceFuture.java
Code in this PR is based on discussion on [this issue](https://github.com/azure/azure-sdk-for-java/issues/6553) filed for `azure-keyvault-extensions` (Track 1 SDK).
> Added flag for keeping track of when value is set in ServiceFuture

- README.md
- azure-arm-client-runtime/pom.xml
- azure-client-authentication/pom.xml
- azure-client-runtime/pom.xml
- build-tools/pom.xml
- client-runtime/pom.xml
- pom.xml
> Release 1.7.5

- client-runtime/src/main/java/com/microsoft/rest/RestClient.java
- client-runtime/src/test/java/com/microsoft/rest/RestClientTests.java
- pom.xml
For https://github.com/Azure/azure-libraries-for-java/issues/1197
> support okhttp protocols

- client-runtime/src/main/java/com/microsoft/rest/Validator.java
- client-runtime/src/test/java/com/microsoft/rest/ValidatorTests.java
Fixes https://github.com/Azure/autorest-clientruntime-for-java/issues/687
> Handle list and map parameters in Validator

- README.md
- azure-arm-client-runtime/pom.xml
- azure-client-authentication/pom.xml
- azure-client-runtime/pom.xml
- azure-client-runtime/src/main/java/com/microsoft/azure/AzureClient.java
- build-tools/pom.xml
- client-runtime/pom.xml
- pom.xml
1. https://github.com/Azure/autorest-clientruntime-for-java/pull/699
2. update version
3. update readme
> Release 1.7.12

- pom.xml
Fixes https://github.com/Azure/azure-sdk-for-java/issues/23225
> Update adal4j to latest 1.6.7
